name: Install
description: Install tooling and dependencies

inputs:
  cdk:
    description: Boolean indicating whether or not to install the AWS CDK

runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install dependencies
      shell: bash
      run: uv sync --locked --all-extras --dev
